"""initial tables

Revision ID: 067fe6c0ba2b
Revises: 
Create Date: 2025-12-12 19:58:25.055224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '067fe6c0ba2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'invoices', 'vendors', ['vendor_id'], ['id'])
    op.add_column('vendors', sa.Column('address', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('email', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('tax_id', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.create_unique_constraint(None, 'vendors', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendors', type_='unique')
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=True)
    op.drop_column('vendors', 'created_at')
    op.drop_column('vendors', 'tax_id')
    op.drop_column('vendors', 'email')
    op.drop_column('vendors', 'phone')
    op.drop_column('vendors', 'address')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    # ### end Alembic commands ###
